---
title: "git_01"
author: "David Barton"
date: "Fall 2025"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Build a Poem with commits to different branches
Our project will be done using a sequence of save and commits and branch actions.
<!-- Do not modify or change any text in "!--" bracketed areas such as this --- these are instructions to
you, if you change any of this the git program will notice it and compromise your git merging strategy !-->

## First Verse 
<!--Put the first five lines of a poem by Lewis Carrol in this section!-->

’Twas brillig, and the slithy toves.  
Did gyre and gimble in the wabe:  
All mimsy were the borogoves,  
And the mome raths outgrabe.  
  
“Beware the Jabberwock, my son!  

## Second Verse
<!--Put the first five lines of a poem by Robert Frost here!-->

Two roads diverged in a yellow wood,  
And sorry I could not travel both.  
And be one traveler, long I stood.  
And looked down one as far as I could.  

To where it bent in the undergrowth;  

## Third Verse
<!--Put the first two verses of The Walrus and the Carpenter here!-->

The sun was shining on the sea,  
Shining with all his might:  
He did his very best to make.  
The billows smooth and bright—  
And this was odd, because it was.  
The middle of the night.  

The moon was shining sulkily,  
Because she thought the sun.  
Had got no business to be there.  
After the day was done—  
“It’s very rude of him,” she said,   
“To come and spoil the fun!”  



## Last Verse
<!--Put a short poem you created using chatGPT of 20 to 30 lines,here!-->
The wanderer, blown off course time and again.  
After he plundered Troy’s sacred heights.  

Of all the cities he saw, the minds he grasped,  
The suffering deep in his heart at sea.  
As he struggled to survive and bring his men home.  
But could not save them, hard as he tried—  
The fools—destroyed by their own recklessness.  
When they ate the oxen of Hyperion the Sun,  
And that god snuffed out their day of return.  

Speak, Immortal One,  
And tell the tale once more in our time.  

By now, all the others who had fought at Troy—  
At least those who had survived the war and the sea—  
Were safely back home. Only Odysseus. Still longed to return to his home and his wife.  
The nymph Calypso, a powerful goddess—  
And beautiful—was clinging to him. In her caverns and yearned to possess him.  
